# golangci-lint configuration file
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 3m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unparam
    - unused
    - staticcheck
    - stylecheck
    - gosec
    - rowserrcheck
    - asciicheck
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - goheader
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - tenv
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

linters-settings:
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: github.com/anthropics/claude-agent-sdk-go
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  goconst:
    min-len: 3
    min-occurrences: 3
  gocognit:
    min-complexity: 20
  gosec:
    severity: low
    confidence: low
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - dupl
        - goconst

    # Exclude shadow checking on err variables
    - text: "shadow: declaration of \"err\""
      linters:
        - govet

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true